name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: [self-hosted, dev]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: cp /root/shtcut-stg-api/.env /root/shtcut-stg-api/_work/shtcut/shtcut/backend/_env
      - run: cp /root/shtcut-stg-api/.env .
      - run: npm install -g yarn
      - run: yarn
      - run: npm install -g pm2
      - run: pm2 restart 0
      - run: pm2 restart 1
      - run: pm2 restart 2
      - run: pm2 restart 3
